# Generated by Django 5.2.5 on 2025-08-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(help_text="A brief description of your business."),
                ),
                (
                    "business_logo",
                    models.ImageField(blank=True, null=True, upload_to="vendor_logos/"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Your business Tax ID or registration number.",
                        max_length=100,
                    ),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True,
                        help_text="Upload a copy of your business license.",
                        upload_to="vendor_licenses/",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin-approved to sell on the platform.",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (filled by admin)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_vendor": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Profile",
                "verbose_name_plural": "Vendor Profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_approved", "created_at"],
                        name="vendors_ven_is_appr_c45a77_idx",
                    ),
                    models.Index(
                        fields=["business_name"], name="vendors_ven_busines_faabdd_idx"
                    ),
                ],
            },
        ),
    ]
